# General Comments about the data set
This table provides the volume of violent crime (murder and nonnegligent manslaughter, rape, robbery, and aggravated assault) and property crime (burglary, larceny-theft, and motor vehicle theft) as reported by city and town law enforcement agencies (listed alphabetically by state) that contributed data to the UCR Program. (Note:  Arson is not included in the property crime total in this table; however, if complete arson data were provided, they will appear in the arson column.)

Population estimation
For the 2013 population estimates used in this table, the FBI computed individual rates of growth from one year to the next for every city/town and county using 2010 decennial population counts and 2011 through 2012 population estimates from the U.S. Census Bureau. Each agency’s rates of growth were averaged; that average was then applied and added to its 2012 Census population estimate to derive the agency’s 2013 population estimate.

# Instructions

We'll use the property crime model you've been working on with, based on the FBI:UCR data. Since your model formulation to date has used the entire New York State 2013 dataset, you'll need to validate it using some of the other crime datasets available at the FBI:UCR website. Options include other states crime rates in 2013 or crime rates in New York State in other years or a combination of these.
__I chose to test the model that I trained on NY to predict what will happen in CA, and see if the model is a good fit for the new data set__

Iterate
Based on the results of your validation test, create a revised model, and then test both old and new models on a new holdout or set of folds.

Include your model(s) and a brief writeup of the reasoning behind the validation method you chose and the changes you made to submit and review with your mentor.

In [106]:
# import all the modules I need
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
pd.set_option('mode.chained_assignment', None)
%matplotlib inline
import seaborn as sns
import math


# import in the data table I downloaded from UCR
df = pd.DataFrame()
df = pd.read_excel(
    "table_8_offenses_known_to_law_enforcement_new_york_by_city_2013.xls", sheet_name='13tbl8ny')

Need to clean by:
- fixing headers (line 3) and deleting rows 0-2
- dropping Rape\n(revised\ndefinition)1 column 
- filling in NaN with 0


Need to create features by:
- changing categorical variables to 0 and 1

In [107]:
df.drop([0, 1, 2], inplace=True)

In [108]:
df.drop('Unnamed: 4', axis=1, inplace=True)

In [109]:
df.columns = df.loc[3].values

In [110]:
df.drop([3, 352, 353, 354], inplace=True)

In [111]:
df['Arson3'] = df['Arson3'].fillna(0)
df

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (legacy definition)2,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft,Arson3
4,Adams Village,1861,0,0,0,0,0,12,2,10,0,0
5,Addison Town and Village,2577,3,0,0,0,3,24,3,20,1,0
6,Akron Village,2846,3,0,0,0,3,16,1,15,0,0
7,Albany,97956,791,8,30,227,526,4090,705,3243,142,0
8,Albion Village,6388,23,0,3,4,16,223,53,165,5,0
9,Alfred Village,4089,5,0,0,3,2,46,10,36,0,0
10,Allegany Village,1781,3,0,0,0,3,10,0,10,0,0
11,Amherst Town,118296,107,1,7,31,68,2118,204,1882,32,3
12,Amityville Village,9519,9,0,2,4,3,210,16,188,6,1
13,Amsterdam,18182,30,0,0,12,18,405,99,291,15,0
14,Arcade Village,2053,0,0,0,0,0,39,3,35,1,0
15,Ardsley Village,4523,5,0,0,3,2,33,4,28,1,0
16,Asharoken Village,658,0,0,0,0,0,2,0,2,0,0
17,Attica Village,2522,2,0,0,0,2,5,0,4,1,0
18,Auburn,27270,96,1,20,22,53,859,132,721,6,0
19,Avon Village,3333,1,0,0,1,0,25,3,20,2,0
20,Baldwinsville Village,7473,5,0,0,1,4,88,10,77,1,0
21,Ballston Spa Village,5418,8,0,0,3,5,94,16,78,0,1
22,Batavia,15374,57,0,7,13,37,559,103,454,2,0
23,Bath Village,5733,15,0,1,3,11,191,32,157,2,2
24,Bedford Town,17627,5,0,0,1,4,156,26,127,3,0
25,Bethlehem Town,34243,13,0,0,3,10,442,50,388,4,0
26,Binghamton,46304,284,3,19,101,161,2349,525,1767,57,0
27,Black River,1410,0,0,0,0,0,14,2,12,0,0
28,Blooming Grove Town,12001,8,0,1,0,7,99,20,72,7,0
29,Bolivar Village,1022,1,0,0,0,1,4,2,2,0,0
30,Bolton Town,2325,2,0,0,0,2,24,4,20,0,0
31,Boonville Village,2054,1,0,0,0,1,20,6,14,0,0
32,Brant Town,2065,4,0,0,1,3,31,9,20,2,0
33,Brewster,2358,0,0,0,0,0,13,3,10,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
322,Tupper Lake Village,3642,3,0,0,0,3,83,22,59,2,0
323,Tuxedo Park Village,615,0,0,0,0,0,0,0,0,0,0
324,Ulster Town,12195,14,0,3,2,9,437,25,410,2,0
325,Utica,61686,361,7,27,102,225,2528,449,1997,82,0
326,Vestal Town,27980,16,0,2,6,8,571,39,523,9,0
327,Walden Village,6887,18,1,2,1,14,142,13,124,5,0
328,Wallkill Town,27940,40,0,3,16,21,767,91,650,26,1
329,Walton Village,3012,6,0,1,0,5,68,18,50,0,0
330,Warsaw Village,3453,6,0,1,0,5,78,5,73,0,0
331,Washingtonville Village,5828,2,0,0,1,1,58,5,51,2,0
332,Waterford Town and Village,8392,4,0,0,0,4,59,6,52,1,0
333,Waterloo Village,5175,11,0,0,3,8,194,23,169,2,0
334,Watertown,28179,109,0,12,16,81,1165,169,953,43,0
335,Watervliet,10245,26,1,3,11,11,242,58,163,21,0
336,Watkins Glen Village,1862,6,0,0,0,6,92,10,80,2,0
337,Waverly Village,4337,5,0,0,1,4,54,9,41,4,0
338,Webster Town and Village,43777,21,0,2,3,16,469,101,361,7,0
339,Weedsport Village,1797,0,0,0,0,0,25,5,20,0,0
340,Wellsville Village,4574,11,0,1,0,10,164,32,129,3,1
341,Westhampton Beach Village,1732,2,0,0,0,2,44,4,37,3,0
342,West Seneca Town,44821,35,1,1,9,24,896,166,710,20,0
343,Whitehall Village,2604,6,0,0,0,6,62,12,49,1,0
344,White Plains,57559,78,1,3,28,46,1232,77,1134,21,0
345,Whitesboro Village,3733,4,0,0,0,4,36,14,21,1,0
346,Whitestown Town,9141,0,0,0,0,0,77,13,61,3,0
347,Woodbury Town,10685,3,0,0,2,1,541,9,529,3,0
348,Woodridge Village,829,7,0,0,0,7,17,8,9,0,0
349,Woodstock Town,5931,2,0,0,0,2,58,13,45,0,0
350,Yonkers,199134,1036,6,25,390,615,2368,470,1662,236,10
351,Yorktown Town,36643,15,0,0,2,13,334,45,287,2,0

In [112]:
df['Population'] = df['Population'].astype(int)
df['Population2'] = df['Population']**2

In [113]:
df['Robbery'] = df['Robbery'].astype(int)
df['Robbery'] = df['Robbery'].apply(lambda x: (x > 0)*1)

In [114]:
df['Murder and\nnonnegligent\nmanslaughter'] = df['Murder and\nnonnegligent\nmanslaughter'].astype(
    int)
df['Murder and\nnonnegligent\nmanslaughter'] = df['Murder and\nnonnegligent\nmanslaughter'].apply(
    lambda x: (x > 0)*1)

In [115]:
from sklearn import linear_model
%matplotlib inline
pd.options.display.float_format = '{:.3f}'.format

# Suppress annoying harmless error.
import warnings
warnings.filterwarnings(action="ignore", module="scipy",
                        message="^internal gelsd")

In [116]:
regr = linear_model.LinearRegression()
regr.fit(df[['Population', 'Population2',
             'Murder and\nnonnegligent\nmanslaughter', 'Robbery']], df['Property\ncrime'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [117]:
regr.coef_

array([ 1.69008467e-02, -1.73980871e-07,  6.15497194e+02,  1.48320688e+02])

In [118]:
regr.score(df[['Population', 'Population2',
               'Murder and\nnonnegligent\nmanslaughter', 'Robbery']], df['Property\ncrime'])

0.9935839631191373

Predictions. First figuring out how many property crimes there would be in Davis with the specification we had earlier.

With Drew, we realized how important it was for population to be in the regression specification. When we took out population, the regr score went way down. We see how adding random noise increases the regr score by overfitting the data.

In [119]:
# predicting the nuber of property crimes in Davis:
regr.predict([[68111, 68111**2, 0, 0]])

array([318.62882533])

In [120]:
regr = linear_model.LinearRegression()
regr.fit(df[['Population2', 'Murder and\nnonnegligent\nmanslaughter',
             'Robbery']], df['Property\ncrime'])
regr.score(df[['Population2', 'Murder and\nnonnegligent\nmanslaughter',
               'Robbery']], df['Property\ncrime'])

0.05208377602595937

In [121]:
regr = linear_model.LinearRegression()
X = df[['Population2', 'Murder and\nnonnegligent\nmanslaughter', 'Robbery']].values
N = np.random.randn(X.shape[0], 10)
X = np.concatenate((X, N), axis=1)
regr.fit(X, df['Property\ncrime'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [122]:
regr.score(X, df['Property\ncrime'])

0.07300583209075984

Now, let's use the new linear regression code that I learned in this lesson to refit the model and check params, pvalues, and the rsquared value for NY

In [123]:
import statsmodels.formula.api as smf
from statsmodels.sandbox.regression.predstd import wls_prediction_std

In [125]:
#rename and change the data type to be numerical instead of an object
df['Property\ncrime'] = df['Property\ncrime'].astype(int)
df['Population2'] = df['Population2'].astype(int)
df['Property_crime'] = df['Property\ncrime']
df['Murder'] = df['Murder and\nnonnegligent\nmanslaughter']

In [93]:
# Re-fit the model here.
linear_formula = 'Property_crime ~ Population + Murder'

# Fit the model to our data using the formula.
lm = smf.ols(formula=linear_formula, data=df).fit()
print(lm.params)
print(lm.pvalues)
print(lm.rsquared)
print(lm.conf_int())

Intercept     24.873
Population     0.017
Murder       654.243
dtype: float64
Intercept    0.491
Population   0.000
Murder       0.000
dtype: float64
0.9934062182812436
                 0       1
Intercept  -46.097  95.844
Population   0.017   0.017
Murder     462.613 845.873

In [71]:
# import in the data table I downloaded for CA
df_CA = pd.DataFrame()
df_CA = pd.read_excel(
    'table_8_offenses_known_to_law_enforcement_california_by_city_2013.xls', sheet_name='13tbl8ca')

In [72]:
df_CA.drop([0, 1, 2], inplace=True)

In [73]:
df_CA.drop('Unnamed: 4', axis=1, inplace=True)

In [74]:
df_CA.columns = df_CA.loc[3].values
df_CA

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (legacy definition)2,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft,Arson
3,City,Population,Violent\ncrime,Murder and\nnonnegligent\nmanslaughter,Rape\n(legacy\ndefinition)2,Robbery,Aggravated\nassault,Property\ncrime,Burglary,Larceny-\ntheft,Motor\nvehicle\ntheft,Arson
4,Adelanto,31165,198,2,15,52,129,886,381,372,133,17
5,Agoura Hills,20762,19,0,2,10,7,306,109,185,12,7
6,Alameda,76206,158,0,10,85,63,1902,287,1285,330,17
7,Albany,19104,29,0,1,24,4,557,94,388,75,7
8,Alhambra,84710,163,1,9,81,72,1774,344,1196,234,7
9,Aliso Viejo,50005,25,0,2,4,19,315,71,224,20,3
10,Alturas,2681,28,1,4,2,21,71,23,46,2,0
11,American Canyon,20068,54,0,4,31,19,510,91,387,32,2
12,Anaheim,345320,1130,11,82,437,600,9611,1412,6518,1681,35
13,Anderson,10098,63,0,8,9,46,721,147,454,120,5
14,Antioch,106447,946,12,25,352,557,4440,1351,1872,1217,57
15,Apple Valley,71159,185,3,12,58,112,1594,596,775,223,22
16,Arcadia,57855,77,0,1,37,39,1518,376,1080,62,3
17,Arcata,17805,67,3,7,15,42,841,147,634,60,14
18,Arroyo Grande,17634,31,0,5,4,22,455,137,288,30,0
19,Artesia,16734,63,2,0,28,33,323,91,177,55,1
20,Arvin,20390,153,2,1,16,134,744,323,308,113,15
21,Atascadero,28938,97,1,12,24,60,544,119,400,25,7
22,Atherton,7278,10,0,1,1,8,115,34,78,3,1
23,Atwater,28906,182,1,7,22,152,1323,361,804,158,5
24,Auburn,13779,49,0,2,13,34,302,86,190,26,7
25,Avalon,3777,4,0,0,2,2,88,13,57,18,1
26,Avenal,14712,62,0,4,6,52,147,63,67,17,2
27,Azusa,47754,246,2,4,36,204,1098,256,671,171,6
28,Bakersfield,361859,1857,24,43,708,1082,16814,4605,9272,2937,193
29,Baldwin Park,76745,220,5,6,74,135,1370,280,727,363,8
30,Banning,30503,129,2,9,26,92,808,355,323,130,0
31,Barstow,23144,229,3,13,45,168,785,329,354,102,11
32,Bear Valley,5328,12,0,1,0,11,111,10,101,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
438,Vista,96712,445,1,28,140,276,2045,390,1326,329,6
439,Walnut,30279,37,0,1,10,26,463,220,207,36,0
440,Walnut Creek,66149,78,0,4,31,43,2161,364,1634,163,1
441,Waterford,8590,29,2,1,4,22,224,78,104,42,0
442,Watsonville,52076,237,3,20,71,143,1308,218,824,266,9
443,Weed,2927,26,0,6,3,17,110,33,74,3,0
444,West Covina,107867,231,1,2,106,122,3370,615,2254,501,2
445,West Hollywood,34902,216,0,14,68,134,1435,292,1044,99,2
446,Westlake Village,8440,11,0,1,3,7,148,40,102,6,1
447,Westminster,91885,283,0,13,84,186,2476,420,1720,336,8
448,Westmorland,2279,2,0,1,1,0,6,2,4,0,0
449,West Sacramento,49751,205,1,16,98,90,1483,380,894,209,9
450,Wheatland,3522,0,0,0,0,0,49,16,28,5,0
451,Whittier,86450,223,3,17,73,130,2383,455,1675,253,4
452,Wildomar,33453,40,0,2,11,27,536,166,287,83,1
453,Williams,5176,5,0,0,3,2,67,24,35,8,1
454,Willits,4832,30,0,1,1,28,61,6,35,20,2
455,Willows,6122,17,0,2,3,12,179,54,116,9,0
456,Windsor,27249,105,0,9,8,88,269,52,209,8,4
457,Winters,6992,8,1,0,3,4,115,27,76,12,2
458,Woodlake,7417,10,1,1,1,7,134,39,79,16,0
459,Woodland,56523,272,1,16,48,207,1942,510,1238,194,34
460,Yorba Linda,67492,30,0,5,6,19,700,172,482,46,1
461,Yountville,2969,1,0,1,0,0,57,17,34,6,0
462,Yreka,7639,49,1,2,2,44,278,71,193,14,2
463,Yuba City,65133,174,2,15,39,118,1980,438,1210,332,16
464,Yucaipa,52524,107,0,7,31,69,926,262,534,130,13
465,Yucca Valley,21214,86,3,7,15,61,429,141,234,54,2
466,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
467,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
df_CA.drop([3, 466, 467], inplace=True)

In [77]:
df_CA['Murder'] = df_CA['Murder and\nnonnegligent\nmanslaughter']
df_CA['Property_crime'] = df_CA['Property\ncrime']

In [78]:
df_CA['Murder'] = df_CA['Murder'].astype(int)
df_CA['Murder'] = df_CA['Murder'].apply(lambda x: (x > 0)*1)

In [85]:
df_CA['Population'] = df_CA['Population'].astype(int)
df_CA['Property_crime'] = df_CA['Property_crime'].astype(int)

In [94]:
# Re-fit the model here to CA 
linear_formula = 'Property_crime ~ Population + Murder'

# Fit the model to our data using the formula.
lm_CA = smf.ols(formula=linear_formula, data=df_CA).fit()
print(lm_CA.params)
# print(lm.pvalues)
# print(lm.rsquared)
# print(lm.conf_int())

Intercept    -57.299
Population     0.024
Murder       589.797
dtype: float64

In [102]:
y_pred = lm.predict(df_CA[['Property_crime', 'Population', 'Murder']])
y = df_CA['Property_crime']
SS_Residual = sum((y - y_pred) ** 2)
SS_Total = sum((y - np.mean(y)) ** 2)
r_squared = 1 - (float(SS_Residual)) / SS_Total
print(r_squared)
print(lm.pvalues)

0.8032009799627111
Intercept    0.491
Population   0.000
Murder       0.000
dtype: float64

We used the linear model that was trained on the NY data set from 2013 and tried it on the 2013 CA data set. This gave us a R^2 value of 0.803.

Next, let's validate our model by comparing how the CA trained linear model will work on the NY data set.

For my model to be trustworthy, I expect the R^2 values to be the same or very similar.

In [103]:
y_pred = lm_CA.predict(df[['Property_crime', 'Population', 'Murder']])
y = df['Property_crime']
SS_Residual = sum((y - y_pred) ** 2)
SS_Total = sum((y - np.mean(y)) ** 2)
r_squared = 1 - (float(SS_Residual)) / SS_Total
print(r_squared)
print(lm_CA.pvalues)

0.7998327830081634
Intercept    0.617
Population   0.000
Murder       0.001
dtype: float64

Yay! The R^2 value is 0.799, very similar to the 0.803 R^2 value from before. So, I conclude that my model is trustworthy.

Future steps:
- apply the NY 2013 linear model I made to another year, say 2015, for NY
- I expect that R^2 values would be closer or improved

- do the fold analysis with 5 groups/folds to see if the components listed at the end give similar values and then I can see whether or not I'm overfitting or not.